apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd
  namespace: itsmetommy
spec:
  selector:
    matchLabels:
      app: argocd
  replicas: 2
  template:
    metadata:
      labels:
        app: argocd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    spec:
      containers:
      - name: argocd
        image: itsmetommy/argocd:2.0
        ports:
        - containerPort: 80