apiVersion: v1
kind: Service
metadata:
  name: argocd
  namespace: itsmetommy
  labels:
    app: argocd
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: argocd